#! /bin/sh
### BEGIN INIT INFO
# Provides:          network
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Network startup in root container
# Description:       Network startup in root container
### END INIT INFO

# Author: Jean Parpaillon <jean.parpaillon@kerlabs.com>
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="root container network"
NAME=network
SCRIPTNAME=/etc/init.d/$NAME
CONF=/etc/kerrighed/$NAME.conf

# Read configuration variable file if it is present
[ -r $CONF ] && . $CONF

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
    log_progress_msg "lo"
    ifconfig lo up

    #BASE_INTERFACE=$(echo "$INTERFACE" | sed 's/:[0-9]\+$//')
    #if [ "$BASE_INTERFACE" != "$INTERFACE" ]; then
	#log_progress_msg "$BASE_INTERFACE"
	#ifconfig $BASE_INTERFACE up
    #fi
    #log_progress_msg "$INTERFACE"
    #ifconfig $INTERFACE $IPADDR netmask $NETMASK
    #log_progress_msg "gw"
    #[ -n "$GATEWAY" ] && route add default gw $GATEWAY
    return $?
}

#
# Function that stops the daemon/service
#
do_stop()
{
    ifconfig $INTERFACE down 
    return 0
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC"
	do_start
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" && exit 0 || exit $?
       ;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
