#!/bin/bash -e
# -------
# File:          kerrighedize
# Description:   makes the machine a master node for Kerrighed cluster
# Author:        Jean Parpaillon <jean.parpaillon@kerlabs.com>
# Copyright:     (c) 2010 Jean Parpaillon <jean.parpaillon@kerlabs.com>
#
trap k_clean ERR

export basedir=$(dirname $0)

if [ "${basedir}" = "/usr/sbin" ]; then
    export libdir=/usr/share/kerrighedize
else
    export libdir=${basedir}/lib
fi
export tftp_dir=/srv/tftp
export kernel_version=

export k_valuesoutput_tmp=$(mktemp)

function k_clean
{
    rm -f ${k_valuesoutput_tmp}
}

function k_check_root
{
    echo -n "Check if user is root... "
    if [ 0 -ne $(id -u) ]
    then
	echo "failed"
	exit 1
    else
	echo "ok"
    fi
}

#
# Load a module
#
function k_load
{
    if [ -z "$1" ]
    then
	echo "k_load(): missing argument"
	exit 1
    fi
	
    module=$1

    if [ -f /etc/debian_version ]
    then
	distro=debian
    fi

    ret=1
    for file in ${module} ${module}_${distro}
    do
	if [ -e ${libdir}/${file} ]
	then
	    . ${libdir}/${file}
	    ret=0
	fi
    done

    if [ "${ret}" -eq "1" ]
    then
	echo "k_load(): no such module in ${libdir}: ${module}"
	exit 1
    fi

    return $ret
}

function usage
{
    echo "Usage: $0 [-h] [-I] [-i conf.in] [-o conf.out]"
    echo "  -h   : print this help"
    echo "  -I   : always ask questions"
    echo "  -i   : load config from this file"
    echo "  -o   : write config to this file for further deployment"
    echo "  -d   : install dhcp on this server (override config file)"
}

export dhcp_enable=
export interactive=
export valueinput=
export valueoutput=

# Load bootstrap modules
k_load log
k_load common

while getopts  "hIi:o:d" flag
do
    case $flag in
	h)
	    usage
	    exit 0
	    ;;
	I)
	    interactive=1
	    ;;
	i)
	    valueinput=$OPTARG
	    if [ ! -e "${valueinput}" ]
	    then
		echo "File not found: ${valueinput}"
		exit 1
	    fi
	    ;;
	o)
	    valuesoutput=$OPTARG
	    ;;
	d)
	    dhcp_enable=1
	    k_save_var dhcp_enable 1
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done

k_check_root

# Load modules
k_load install
k_load packages
k_load dhcp
k_load nfs
k_load tftp
k_load pxe
k_load bootloader
k_load misc

k_dhcp_init

# Run steps
k_step_install
[ ${dhcp_enable} -eq 1 ] && k_step_dhcp
k_step_tftp
k_step_pxe
k_step_nfsserver
k_step_bootloader
k_step_misc

# Cleanup
if [ -n "${valuesoutput}" ]
then
    cp ${k_valuesoutput_tmp} ${valuesoutput}
fi
k_clean

exit 0
