#!/bin/bash -e
#
# bootloader functions (Debian)
function k_bootloader_grub2
{
    [ -e /etc/default/grub.krg-bak ] || mv /etc/default/grub /etc/default/grub.krg-bak
    cat /etc/default/grub.krg-bak | sed -e 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT="Kerrighed '$kernel_version'"/' > /etc/default/grub

    k_log_progress "Update GRUB 2"
    update-grub > /dev/null
    if [ 0 -eq $? ]; then
	k_log_success
    else
	k_log_error
    fi
}
