#!/bin/bash -e
#
# bootloader functions
function k_step_bootloader
{
    k_log_progress "Setup Kerrighed boot parameters"
    # May be used by /etc/grub.d/09_kerrighed
    local bootparams="session_id=1 init=/sbin/init-krg boot_id=1 autonodeid=0 node_id=1"
    if [ ${dhcp_enable} -eq 0 ]; then
	bootparams="${bootparams} ip=dhcp"
    else
	# ip=<client-ip>:<server-ip>:<gw-ip>:<netmask>:<hostname>:<device>:<autoconf>
	bootparams="${bootparams} ip=$(k_ip_first ${dhcp_network}):::255.255.255.0::${dhcp_interface}:"
    fi
    echo ${bootparams} > /etc/kerrighed/bootparams.conf
    k_log_success

    if which grub-mkconfig > /dev/null; then
	# Should be GRUB2
	k_bootloader_grub2
    else
	# Other should be handled correctly by boottool
	k_bootloader_boottool
    fi
}

function k_bootloader_grub2
{
    k_log_progress "k_bootloader_grub2(): not implemented"
    k_log_error
    exit 1
}

function k_bootloader_boottool
{
    k_log_progress "k_bootloader_boottool(): not implemented"
    k_log_error
    exit 1
}
