#!/bin/bash -e
#
# dhcp functions (Debian specific)
dhcp_packages=dnsmasq

function k_configure_dhcp_distro
{
    k_log_progress "Setup dnsmasq startup scripts"
    [ -e /etc/default/dnsmasq.krg-bak ] || mv /etc/default/dnsmasq /etc/default/dnsmasq.krg-bak
    cat > /etc/default/dnsmasq <<EOF
ENABLED=1
CONFIG_DIR=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new
EOF

    update-rc.d -f dnsmasq remove > /dev/null

    # /etc/kerrighed/rcmaster/start.d
    level=/etc/kerrighed/rcmaster/start.d
    ln -fs ../../../init.d/dnsmasq ${level}/S20dnsmasq

    # /etc/kerrighed/rcmaster/halt.d
    level=/etc/kerrighed/rcmaster/halt.d
    ln -fs ../../../init.d/dnsmasq ${level}/K10dnsmasq

    # /etc/kerrighed/rcmaster/reboot.d
    level=/etc/kerrighed/rcmaster/reboot.d
    ln -fs ../../../init.d/dnsmasq ${level}/K10dnsmasq

    k_log_success
}
