#!/bin/bash -e
#
# install functions
scripts="\
	usr/sbin/boottool sbin/init-krg \
	etc/grub.d/09_kerrighed etc/init.d/krgtftp \
        etc/init.d/krgdnsmasq etc/init.d/krghalt \
        etc/init.d/krghostname.sh etc/init.d/krgexport \
        etc/init.d/krgreboot etc/init.d/krgremount \
        etc/init.d/krgsshd etc/init.d/krglast \
        etc/init.d/krgdiskless usr/sbin/krgctnrinit \
        etc/init.d/krgnetwork \
"
datas="\
        lib/init/kerrighed-functions \
        etc/default/krgdnsmasq etc/default/krgexport \
        etc/default/krgremount etc/default/krgsshd \
        etc/network/interfaces.diskless \
"

distdir=${basedir}/dist
install_scripts="install -D -m 755 -o root -g root"
install_data="install -D -m 644 -o root -g root"
install_dir="install -m 755 -o root -g root -d"

function k_step_install
{
    if [ -z "${basedir}" ]
    then
	echo "k_step_install: undefined \$basedir"
	exit 1
    fi

    if [ "${basedir}" = "/usr/sbin" ]; then
	# If installed /usr/sbin, consider skipping this step
	return 0
    fi

    ret=0
    k_log "Install files...\n"
    for file in ${scripts}; do
	k_log "\tscript: ${file}\n"
	${install_scripts} ${distdir}/${file} /${file}
	[ 0 -eq $? ] || return 1
    done
    for file in ${datas}; do
	k_log "\tdata  : ${file}\n"
	${install_data} ${distdir}/${file} /${file}
	[ 0 -eq $? ] || return 1
    done

    return $ret
}
