#!/bin/bash -e
#
# misc functions
function k_step_misc
{
    k_misc_master
}

function k_misc_master
{
    services="krghalt krghostname.sh krgreboot krgremount krgsshd kerrighed krglast krgdiskless"
    for service in $services; do
	k_enable_service $service
    done

    # Setup krginit_helper
    echo "KRGINIT_ARGS='-- /usr/sbin/sshd -D'" > /etc/kerrighed/krginit_helper.conf
}
