#!/bin/bash -e
#
# nfs functions 
function k_step_nfsserver
{
    if ! k_check_package ${nfs_packages}
    then
	k_install_package ${nfs_packages}
    fi
    k_configure_nfs
    k_configure_nfs_distro
}

function k_configure_nfs
{
    k_enable_service krgexport
}

function k_configure_nfs_distro
{
    true
}