#!/bin/bash -e
#
# PXE functions (Debian implementation)
pxe_packages="syslinux initramfs-tools"

function k_configure_pxe_distro
{
    ln -fs /usr/lib/syslinux/pxelinux.0 ${tftp_dir}/pxelinux.0
}

function k_make_initrd
{
    if [ -z "${1}" ]
    then
	echo "k_make_initrd(): missing argument" >&2
	exit 1
    fi
    v=${1}
    ret=0

    k_log_progress "Creating initramfs for NFSROOT boot (${v})"
    cat > /etc/initramfs-tools/initramfs.conf.nfs <<EOF
MODULES=most
BUSYBOX=y
KEYMAP=n
COMPRESS=gzip
BOOT=nfs
DEVICE=
NFSROOT=auto
EOF

    [ -e /etc/initramfs-tools/initramfs.conf.krg-bak ] || \
	cp /etc/initramfs-tools/initramfs.conf /etc/initramfs-tools/initramfs.conf.krg-bak
    rm -f /etc/initramfs-tools/initramfs.conf
    ln -fs initramfs.conf.nfs /etc/initramfs-tools/initramfs.conf
    rm -f ${tftp_dir}/initrd.img-${v}
    update-initramfs -k ${v} -b ${tftp_dir} -c > /dev/null
    ret=$?

    if [ 0 -eq $ret ]; then
	k_log_success
    else
	k_log_error
    fi
    return $?
}

function k_get_local_linux_cmdline
{
    awk -F'=' '/^GRUB_CMDLINE_LINUX_DEFAULT/ { print $2 }' /etc/default/grub
}
