#!/bin/bash -e
#
# tftp functions 
#k_load_var tftp_dir

function k_step_tftp
{
    if ! k_check_package ${tftp_packages}
    then
	k_install_package ${tftp_packages}
    fi
    k_configure_tftp_distro
    k_configure_tftp
}

function k_configure_tftp_distro
{
    k_log_progress "k_configure_tftp_distro(): not implemented"
    k_log_error
    exit 1
}

function k_configure_tftp
{
    k_disable_service atftpd
    k_enable_service krgtftp
    mkdir -p ${tftp_dir}
}
