#!/bin/bash -e
#
# tftp functions 
#k_load_var tftp_dir

function k_step_tftp
{
    if ! k_check_package ${tftp_packages}
    then
	k_install_package ${tftp_packages}
    fi
    k_configure_tftp_distro
    k_configure_tftp
}

function k_configure_tftp_distro
{
    k_log_progress "k_configure_tftp_distro(): not implemented"
    k_log_error
    exit 1
}

function k_configure_tftp
{
    k_log_progress "Setup TFTP startup scripts"
    # /etc/kerrighed/rcmaster/start.d
    level=/etc/kerrighed/rcmaster/start.d
    ln -fs ../../../init.d/atftpd ${level}/S20atftpd

    # /etc/kerrighed/rcmaster/halt.d
    level=/etc/kerrighed/rcmaster/halt.d
    ln -fs ../../../init.d/atftpd ${level}/K10atftpd
    
    # /etc/kerrighed/rcmaster/reboot.d
    level=/etc/kerrighed/rcmaster/reboot.d
    ln -fs ../../../init.d/atftpd ${level}/K10atftpd

    mkdir -p ${tftp_dir}
    k_log_success
}
