#!/bin/bash -e
#
# tftp functions (Debian implementation)
tftp_packages=atftpd

function k_configure_tftp_distro
{
    k_log_progress "Setup TFTP startup scripts"
    update-rc.d -f atftp remove > /dev/null

    cat >> /etc/default/atftpd <<EOF
USE_INETD=false
OPTIONS="--tftpd-timeout 300 --retry-timeout 5 --mcast-port 1758 --mcast-addr 239.239.239.0-255 --mcast-ttl 1 --maxthread 100 --verbose=5 ${tftp_dir}"
EOF

    if which update-inetd > /dev/null
    then
	update-inetd --disable tftp > /dev/null
    fi
    k_log_success
}
